php:
  - 5.4
  - 5.5
  - 5.6
  - HHVM

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpspec run -v
  - vendor/bin/behat -v